name: Test

run-name: ${{ github.actor }} is testing the app

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - '**.yaml'
      - 'doc/**'
      - '.git/'
      - '.vscode/'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Check Version
        run: flutter --version
      - name: Flutter Doctor
        run: flutter doctor -v
      - name: Run Tests
        run: flutter test